---
site:
  baseUrl: "https://docs.elhub.cloud/common/common-orchid-theme"
  theme: Elhub
  about:
    siteName: common-orchid-theme

kotlindoc:
  sourceDirs:
    - "../src/main/kotlin"
  args: ["-include", "packages.md"]

Elhub:
  legacySearch: false
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: "wiki"
      asSubmenu: true
      submenuTitle: Guide Book
    - type: "pages"
      group: "adr"
      asSubmenu: true
      submenuTitle: "Decisions"
    - type: "sourcedocPages"
      moduleType: "kotlindoc"
      node: "packages"
      asSubmenu: true
      submenuTitle: "Reference"
    - type: "pages"
      group: "about"
      asSubmenu: true
      submenuTitle: "About"
