---
site:
#  baseUrl: "https://docs.elhub.cloud/common/common-orchid-theme
  baseUrl: "http://localhost:8080"
  about:
    siteName: common-orchid-theme

kotlindoc:
  sourceDirs:
    - '../src/main/kotlin'
  args: ["-include", "packages.md"]

Elhub:
#  primaryColor: "#006600"
#  secondaryColor: "#000000"
#  linkColor: "#0096a9"
  legacySearch: false
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: "wiki"
      asSubmenu: true
      submenuTitle: Guide Book
    - type: "pages"
      group: "adr"
      asSubmenu: true
      submenuTitle: "Decisions"
    - type: "sourcedocPages"
      moduleType: "kotlindoc"
      node: "packages"
      asSubmenu: true
      submenuTitle: "Reference"
